import { choice, type Questions } from "@typesafe-ai/sdk";
import { GRAPH, validateMap, type AppMap, type Finding, type Seed } from "./graph.js";
import { LEGACY_CONTENT_CANDIDATES as WHOLE_CANDIDATES } from "./whole.js";
import type { Answers } from "./decisions.js";
import { supportedPath } from "./consequences.js";

interface JourneyTemplate { id: string; task: string; owner: string; steps: string[]; activity: string; shortcut?: [string, string] }
const journeyTemplates: JourneyTemplate[] = [
  { id: "discover", task: "Discover primary content, inspect an item, and start using it", owner: "w_browse", steps: ["home", "w_browse", "w_collection", "w_item", "w_active"], activity: "Control experience", shortcut: ["w_browse", "w_item"] },
  { id: "find", task: "Find a particular item and start using it", owner: "w_search", steps: ["home", "w_search", "w_item", "w_active"], activity: "Control experience", shortcut: ["w_search", "w_active"] },
  { id: "saved", task: "Open saved or followed content and start using an item", owner: "w_library", steps: ["home", "w_library", "w_item", "w_active"], activity: "Control experience", shortcut: ["w_library", "w_active"] },
  { id: "offline", task: "Find a downloaded item and use it", owner: "w_downloads", steps: ["home", "w_downloads", "w_item", "w_active"], activity: "Control experience", shortcut: ["w_downloads", "w_active"] },
  { id: "queue", task: "Inspect and manage the upcoming items of an active experience", owner: "w_queue", steps: ["home", "w_library", "w_item", "w_active", "w_queue"], activity: "Manage items", shortcut: ["home", "w_queue"] },
  { id: "history", task: "Find a recent item and resume using it", owner: "w_activity", steps: ["home", "w_activity", "w_item", "w_active"], activity: "Control experience", shortcut: ["w_activity", "w_active"] },
  { id: "account", task: "Find account information and open the existing settings overview", owner: "w_profile", steps: ["home", "w_profile", "first"], activity: "Use observed settings controls", shortcut: ["home", "first"] },
  { id: "create", task: "Create or book a new primary record, then save or cancel", owner: "w_create", steps: ["home", "w_create"], activity: "Save" },
  { id: "help", task: "Find product help, then return to the app", owner: "w_help", steps: ["home", "w_help"], activity: "Read help" },
];
/** Select a concrete scope for one plausible design; no probability threshold or unknown edge state. */
export function proposalScopeQuestions(): Questions {
  return Object.fromEntries(journeyTemplates.map((t) => [`scope_${t.id}`, choice({
    context: "Choose a concrete scope for ONE plausible app consistent with the original brief and first screen. We are making design choices, not proving unique intent. Include core surrounding tasks implied by the app domain. Omit unrelated product capabilities and speculative features. Sample values are irrelevant. No screen is generated by this decision.",
    question: `Should this proposed app include the task: ${t.task}? This is a product-scope choice. Creating or booking a primary record means creating a new domain object, not merely saving a preference or adding an existing item to a collection.`,
  }, { include: "Include this task in this app design.", omit: "Leave this task outside this app design." })]));
}
export function scopeExclusions(answers: Answers): Set<string> {
  const excluded = new Set<string>();
  for (const t of journeyTemplates) {
    const value = answers[`scope_${t.id}`]?.choice;
    if (value === "omit") excluded.add(t.id);
    else if (value !== "include") throw new Error(`Invalid concrete scope choice for ${t.id}`);
  }
  return excluded;
}
export interface JourneyReview {
  id: string; task: string; owner: string; path: string[] | null; returnPath: string[] | null;
  activity: string; activityAvailable: boolean; repair?: [string, string];
  verdict?: string; p?: number; probabilities?: Record<string, number>;
}
export interface ProposalReview {
  journeys: JourneyReview[]; findings: Finding[];
  repairs: Array<{ question: string; kind: "shortcut" | "prune"; owner: string; edge?: [string, string] }>;
  coverage?: { verdict: string; p: number; probabilities: Record<string, number> };
}
function addEdge(map: AppMap, from: string, to: string, kind: "navigate" | "back" = "navigate") {
  if (from === to) return;
  const node = map.nodes.find((n) => n.id === from), target = map.nodes.find((n) => n.id === to);
  if (!node || !target) throw new Error(`Cannot create proposed link ${from} → ${to}`);
  if (node.actions.some((a) => a.target === to && ["navigate", "back"].includes(a.kind))) return;
  node.actions.push({ id: `to_${to}`, label: kind === "back" ? `Back to ${target.label}` : target.label, kind, target: to, sourceLink: null });
}

/** A complete code-authored design hypothesis. No confidence gates or dangling candidate edges. */
export function proposeApp(base: AppMap): AppMap {
  if (base.nodes.length + WHOLE_CANDIDATES.length > 24) throw new Error("Proposal exceeds the finite destination budget.");
  const map = structuredClone(base);
  map.boundary = "A complete proposed app within a finite role grammar. Every link is executable; concrete journeys are critiqued before the hypothesis is called reviewed. Design choices are provisional, not facts inferred from probabilities.";
  for (const c of WHOLE_CANDIDATES) map.nodes.push({ id: c.id, label: c.label, purpose: c.purpose, actions: [] });
  for (const t of journeyTemplates) for (let i = 1; i < t.steps.length; i++) {
    const from = t.steps[i - 1] === "home" ? map.home : t.steps[i - 1], to = t.steps[i] === "home" ? map.home : t.steps[i];
    // The rendered first screen retains exactly its observed actions.
    if (from !== "first") addEdge(map, from, to);
  }
  addEdge(map, "w_library", "w_collection");
  // Return routes are explicit. They reuse canonical destinations, never fresh mocks.
  for (const c of WHOLE_CANDIDATES) addEdge(map, c.id, map.home, "back");
  for (const id of ["w_browse", "w_search", "w_library", "w_collection", "w_item", "w_queue", "w_downloads", "w_activity"]) {
    map.nodes.find((n) => n.id === id)!.actions.push({ id: "manage", label: "Manage items", kind: "in_place", target: null, sourceLink: null });
  }
  map.nodes.find((n) => n.id === "w_active")!.actions.push({ id: "control", label: "Control experience", kind: "in_place", target: null, sourceLink: null });
  map.nodes.find((n) => n.id === "w_create")!.actions.push({ id: "save", label: "Save", kind: "complete", target: null, sourceLink: null });
  // If first is itself home, adding unobserved links to that existing mock is not permitted.
  // The validator will expose unsupported reachability rather than fabricate controls on it.
  return GRAPH.parse(map);
}

/** All paths are calculated from actual edges. A removed task stays recorded as out of scope. */
export function concreteJourneys(map: AppMap, excluded: Set<string> = new Set()): JourneyReview[] {
  return journeyTemplates.filter((t) => !excluded.has(t.id)).map((t) => {
    const end = t.steps.at(-1)!, owner = t.owner;
    const entry = supportedPath(map, map.home, owner);
    const onward = supportedPath(map, owner, end);
    const path = entry && onward ? [...entry, ...onward.slice(1)] : null;
    const shortcut = t.shortcut?.map((id) => id === "home" ? map.home : id) as [string, string] | undefined;
    const repair = shortcut && shortcut[0] !== "first" && shortcut.every((id) => map.nodes.some((n) => n.id === id))
      && !map.nodes.find((n) => n.id === shortcut[0])!.actions.some((a) => a.target === shortcut[1] && ["navigate", "back"].includes(a.kind)) ? shortcut : undefined;
    const endNode = map.nodes.find((n) => n.id === end);
    const activityAvailable = t.activity === "Read help" ? !!endNode : t.activity === "Use observed settings controls" ? !!endNode?.actions.length : !!endNode?.actions.some((a) => a.label === t.activity && ["in_place", "complete"].includes(a.kind));
    return { activityAvailable, id: t.id, task: t.task, owner, path, returnPath: supportedPath(map, end, map.home), activity: t.activity, ...(repair ? { repair } : {}) };
  });
}
export function journeyQuestions(map: AppMap, journeys: JourneyReview[], excluded: string[]): Questions {
  const context = "Review an explicit proposed app design. It is a hypothesis to improve, not a claim of the uniquely correct architecture. Multiple designs can work. The goal is one plausible fully resolved IA, not the uniquely correct or ideal app. When the brief allows several options, treat the explicit proposal as a design assumption and test it on its own terms. Keep a coherent journey even if another design is also reasonable. Use the original brief and first-screen evidence to decide which surrounding tasks belong. Critique an actual task failure, not low probability or mere preference. Do not approve empty apps by removing core tasks. No later saved mocks or sample values are evidence.";
  const label = (id: string) => map.nodes.find((n) => n.id === id)?.label ?? id;
  const questions: Questions = {};
  for (const j of journeys) {
    questions[`journey_${j.id}`] = choice({ context, question: `Task: ${j.task}. Proposed path: ${j.path?.map(label).join(" → ") ?? "NO ROUTE"}. At the destination: ${j.activity} (${j.activityAvailable ? "represented" : "MISSING"}). Return: ${j.returnPath?.map(label).join(" → ") ?? "NO RETURN"}. Assess this actual experience. Select works when it reasonably completes the task; competing designs are not a defect.` }, {
      works: "Keep this journey: it reasonably completes a task that belongs in this app.",
      ...(j.repair ? { shortcut: `The proposed route materially impedes this task. Repair it by adding ${label(j.repair[0])} → ${label(j.repair[1])}; then assess the changed journey again.` } : {}),
      unnecessary: "This whole task is outside the intended core app. Remove its task-specific entry/destination, preserving shared responsibilities used by other tasks.",
      wrong_scope: "A screen responsibility or local activity contradicts the task. The available link repair cannot fix it.",
      missing: "The task belongs, but a necessary responsibility or action is absent from the candidate vocabulary.",
      unknown: "The brief and proposed experience are insufficient to assess this task.",
    });
  }
  questions.coverage = choice({ context, question: `Does the complete proposed map cover the core surrounding app implied by the brief and first screen? Independently inspect its actual responsibilities, local actions and journeys. Tasks already excluded: ${excluded.join(", ") || "none"}. Identify missing core work even if each remaining journey appears individually reasonable. A bounded vocabulary or a closed graph is not proof of completeness.` }, {
    works: "The map covers the core app within this experiment's scope; its tasks compose coherently.",
    missing: "A core task, responsibility or action is missing; the finite vocabulary needs revision.",
    conflict: "The responsibilities or task flows conflict or duplicate each other materially.",
    unknown: "The evidence is insufficient to establish app-wide coverage.",
  });
  return questions;
}

/** No .65 gate: judgments select design revisions. Unknown is a review finding, not a missing edge. */
export function reviewProposal(map: AppMap, journeys: JourneyReview[], answers: Answers, seed: Seed): ProposalReview {
  const findings = validateMap(map, seed), repairs: ProposalReview["repairs"] = [];
  const reviewed = journeys.map((j) => {
    const a = answers[`journey_${j.id}`];
    if (!a) throw new Error(`Missing journey judgment: ${j.id}`);
    const verdict = a.choice;
    const out = { ...j, verdict, p: a.probabilities[verdict], probabilities: a.probabilities };
    if (verdict === "works" && j.path && j.returnPath && j.activityAvailable) return out;
    if (verdict === "shortcut" && j.repair) repairs.push({ question: j.id, kind: "shortcut", owner: j.owner, edge: j.repair });
    else if (verdict === "unnecessary") repairs.push({ question: j.id, kind: "prune", owner: j.owner });
    else findings.push({ id: `journey:${j.id}`, severity: "uncertain", detail: `${j.task}: ${verdict === "works" ? "the claimed working journey has no executable route, return or required local action" : verdict}.`, p: out.p });
    return out;
  });
  const a = answers.coverage;
  if (!a) throw new Error("Missing app-wide coverage judgment");
  if (a.choice !== "works") findings.push({ id: "coverage", severity: "uncertain", detail: `App-wide critique: ${a.choice}. The map remains executable but its coverage is not established.`, p: a.probabilities[a.choice] });
  return { journeys: reviewed, repairs, findings, coverage: { verdict: a.choice, p: a.probabilities[a.choice], probabilities: a.probabilities } };
}

export function repairProposal(map: AppMap, review: ProposalReview, excluded: Set<string>, protectedIDs: Set<string>) {
  const next = structuredClone(map), nextExcluded = new Set(excluded), receipts: string[] = [];
  for (const repair of review.repairs) {
    if (repair.kind === "shortcut") { addEdge(next, ...repair.edge!); receipts.push(`Journey ${repair.question}: added ${repair.edge!.join(" → ")}.`); }
    else { nextExcluded.add(repair.question); receipts.push(`Journey ${repair.question}: excluded task by explicit critique; shared destinations are preserved.`); }
  }
  const remaining = journeyTemplates.filter((t) => !nextExcluded.has(t.id));
  const needed = new Set([...protectedIDs, ...remaining.flatMap((t) => t.steps.map((id) => id === "home" ? map.home : id))]);
  // Keep a role that carries a retained journey even if its own separate task was excluded.
  for (const j of review.journeys.filter((j) => !nextExcluded.has(j.id))) for (const id of [...(j.path ?? []), ...(j.returnPath ?? [])]) needed.add(id);
  next.nodes = next.nodes.filter((n) => needed.has(n.id));
  for (const node of next.nodes) node.actions = node.actions.filter((a) => !a.target || needed.has(a.target));
  return { map: GRAPH.parse(next), excluded: nextExcluded, receipts };
}
